### ISSUE TITLE
YAML issue in Lab 6 nand Lab 7

### ISSUE THREAD

**Issue by tylerfarmer1** [MicrosoftLearning/PL-7002-Create-and-Manage-Automated-Processes-by-using-Power-Automate#7]
When you open the Instructions for Lab 6 or Lab 7, you get these errors:

![image](https://github.com/MicrosoftLearning/PL-7002-Create-and-Manage-Automated-Processes-by-using-Power-Automate/assets/72703514/a59863ce-cb55-4050-a820-7fd23fa5ba8e)

**Comment by ephiax20** [comment]
I've fixed this in a big PR coming soon, it's due to the ' in the Module name getting parsed as part of the header.
